name: hello
description: A flutter app that says hello

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.2.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true